/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.main;

import static br.com.main.Controle.jdpPrincipal;

/**
 *
 * @author Philco
 */
public class AberturaCaixa extends javax.swing.JInternalFrame {

    /**
     * Creates new form AberturaCaixa
     */
    public AberturaCaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfTroco = new javax.swing.JTextField();
        jtfTotalCaixa = new javax.swing.JTextField();
        jlbNome1 = new javax.swing.JLabel();
        jlbNome2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jcbMesa = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jtfTotal = new javax.swing.JTextField();
        jtfEntrada = new javax.swing.JTextField();
        jtfTrocoCliente = new javax.swing.JTextField();
        jlbNome3 = new javax.swing.JLabel();
        jlbNome4 = new javax.swing.JLabel();
        jlbNome5 = new javax.swing.JLabel();
        jbtAbrirCaixa = new javax.swing.JButton();
        jbtFinalizarVenda = new javax.swing.JButton();
        jbtEncerrarCaixa = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Abrir Caixa");
        getContentPane().setLayout(null);
        getContentPane().add(jtfTroco);
        jtfTroco.setBounds(430, 10, 80, 30);
        getContentPane().add(jtfTotalCaixa);
        jtfTotalCaixa.setBounds(110, 10, 70, 30);

        jlbNome1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome1.setText("TROCO");
        getContentPane().add(jlbNome1);
        jlbNome1.setBounds(570, 270, 90, 30);

        jlbNome2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome2.setText("ENTRADA DE TROCO");
        getContentPane().add(jlbNome2);
        jlbNome2.setBounds(310, 10, 120, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 50, 730, 10);

        jcbMesa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbMesa);
        jcbMesa.setBounds(20, 100, 130, 20);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 100, 380, 280);
        getContentPane().add(jtfTotal);
        jtfTotal.setBounds(570, 140, 110, 30);
        getContentPane().add(jtfEntrada);
        jtfEntrada.setBounds(570, 220, 110, 30);
        getContentPane().add(jtfTrocoCliente);
        jtfTrocoCliente.setBounds(570, 300, 110, 30);

        jlbNome3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome3.setText("CAIXA ABERTO");
        getContentPane().add(jlbNome3);
        jlbNome3.setBounds(20, 10, 90, 30);

        jlbNome4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome4.setText("ENTRADA");
        getContentPane().add(jlbNome4);
        jlbNome4.setBounds(570, 190, 90, 30);

        jlbNome5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome5.setText("TOTAL");
        getContentPane().add(jlbNome5);
        jlbNome5.setBounds(570, 110, 90, 30);

        jbtAbrirCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbtAbrirCaixa.setText("ABRIR CAIXA");
        jbtAbrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAbrirCaixaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtAbrirCaixa);
        jbtAbrirCaixa.setBounds(530, 10, 160, 30);

        jbtFinalizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbtFinalizarVenda.setText("FINALIZAR VENDA");
        jbtFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFinalizarVendaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtFinalizarVenda);
        jbtFinalizarVenda.setBounds(520, 400, 160, 30);

        jbtEncerrarCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbtEncerrarCaixa.setText("ENCERRAR CAIXA");
        jbtEncerrarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEncerrarCaixaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtEncerrarCaixa);
        jbtEncerrarCaixa.setBounds(20, 400, 160, 30);

        setBounds(310, 70, 734, 483);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAbrirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAbrirCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAbrirCaixaActionPerformed

    private void jbtFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFinalizarVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtFinalizarVendaActionPerformed

    private void jbtEncerrarCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEncerrarCaixaActionPerformed
         RelatorioCaixa obj=new RelatorioCaixa();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jbtEncerrarCaixaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtAbrirCaixa;
    private javax.swing.JButton jbtEncerrarCaixa;
    private javax.swing.JButton jbtFinalizarVenda;
    private javax.swing.JComboBox jcbMesa;
    private javax.swing.JLabel jlbNome1;
    private javax.swing.JLabel jlbNome2;
    private javax.swing.JLabel jlbNome3;
    private javax.swing.JLabel jlbNome4;
    private javax.swing.JLabel jlbNome5;
    private javax.swing.JTextField jtfEntrada;
    private javax.swing.JTextField jtfTotal;
    private javax.swing.JTextField jtfTotalCaixa;
    private javax.swing.JTextField jtfTroco;
    private javax.swing.JTextField jtfTrocoCliente;
    // End of variables declaration//GEN-END:variables
}
