/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.main;

import javax.swing.JOptionPane;

/**
 *
 * @author Philco
 */
public class AlterarFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form a
     */
    public AlterarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtAlterarCadastro = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton3 = new javax.swing.JButton();
        jlbNome = new javax.swing.JLabel();
        jlbTelefone = new javax.swing.JLabel();
        jlbCpf = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbUsuario = new javax.swing.JLabel();
        jlbFuncionario = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfTelefone = new javax.swing.JTextField();
        jtfCpf = new javax.swing.JTextField();
        jtfUsuario = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jlbSenha1 = new javax.swing.JLabel();
        jcbRealidade = new javax.swing.JComboBox();
        jcbSetor1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("ATERAR DADOS DO FUNCIONARIO");
        getContentPane().setLayout(null);

        jbtAlterarCadastro.setText("ALTERAR CADASTRO");
        jbtAlterarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(jbtAlterarCadastro);
        jbtAlterarCadastro.setBounds(70, 340, 240, 30);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setTitle("ALTERAR CADASTRO DE FUNCIONARIO");
        jInternalFrame1.getContentPane().setLayout(null);

        jButton3.setText("ALTERAR CADASTRO");
        jInternalFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(10, 244, 410, 23);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 0, 109, 33);

        jlbNome.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome.setText("NOME:");
        getContentPane().add(jlbNome);
        jlbNome.setBounds(20, 40, 70, 30);

        jlbTelefone.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbTelefone.setText("TELEFONE:");
        getContentPane().add(jlbTelefone);
        jlbTelefone.setBounds(20, 120, 100, 30);

        jlbCpf.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbCpf.setText("CPF:");
        getContentPane().add(jlbCpf);
        jlbCpf.setBounds(20, 80, 60, 30);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("SETOR:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 160, 80, 30);

        jlbUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbUsuario.setText("USUARIO:");
        getContentPane().add(jlbUsuario);
        jlbUsuario.setBounds(20, 200, 70, 30);

        jlbFuncionario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbFuncionario.setText("FUNCIONARIO: ");
        getContentPane().add(jlbFuncionario);
        jlbFuncionario.setBounds(20, 290, 100, 30);

        jtfNome.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        getContentPane().add(jtfNome);
        jtfNome.setBounds(70, 40, 250, 30);
        getContentPane().add(jtfTelefone);
        jtfTelefone.setBounds(90, 120, 120, 30);
        getContentPane().add(jtfCpf);
        jtfCpf.setBounds(70, 80, 110, 30);
        getContentPane().add(jtfUsuario);
        jtfUsuario.setBounds(80, 200, 132, 30);
        getContentPane().add(jpfSenha);
        jpfSenha.setBounds(80, 240, 130, 30);

        jlbSenha1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbSenha1.setText("SENHA:");
        getContentPane().add(jlbSenha1);
        jlbSenha1.setBounds(20, 240, 80, 30);

        jcbRealidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Desabilitado" }));
        getContentPane().add(jcbRealidade);
        jcbRealidade.setBounds(120, 290, 150, 30);

        jcbSetor1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adiministrador", "Cozinheiro", "Caixa", "Garçom" }));
        jcbSetor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSetor1ActionPerformed(evt);
            }
        });
        getContentPane().add(jcbSetor1);
        jcbSetor1.setBounds(80, 160, 170, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 0, 0);

        setBounds(480, 160, 385, 412);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbSetor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSetor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSetor1ActionPerformed

    private void jbtAlterarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarCadastroActionPerformed
     
    }//GEN-LAST:event_jbtAlterarCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtAlterarCadastro;
    private javax.swing.JComboBox jcbRealidade;
    private javax.swing.JComboBox jcbSetor1;
    private javax.swing.JLabel jlbCpf;
    private javax.swing.JLabel jlbFuncionario;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbSenha1;
    private javax.swing.JLabel jlbTelefone;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfTelefone;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
