/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.main;

import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Philco
 */
public class CadastroFuncionario extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form jifCadastroFuncionarios
     */
    public CadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlbNome = new javax.swing.JLabel();
        jlbTelefone = new javax.swing.JLabel();
        jlbCpf = new javax.swing.JLabel();
        jlbAdmissao = new javax.swing.JLabel();
        jlbUsuario = new javax.swing.JLabel();
        jlbSenha = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfTelefone = new javax.swing.JTextField();
        jtfCpf = new javax.swing.JTextField();
        jtfAdmissao = new javax.swing.JTextField();
        jbCadastro = new javax.swing.JButton();
        jbtAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbMostrarTodos = new javax.swing.JTable();
        jlbTitulo1 = new javax.swing.JLabel();
        jlbTitulo2 = new javax.swing.JLabel();
        jcbSetor = new javax.swing.JComboBox();
        jpfSenha = new javax.swing.JPasswordField();
        jlbSetor1 = new javax.swing.JLabel();
        jtfUsuario1 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setTitle("CADASTRO FUNCIONARIO");
        getContentPane().setLayout(null);

        jlbNome.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome.setText("NOME:");
        getContentPane().add(jlbNome);
        jlbNome.setBounds(20, 40, 70, 30);

        jlbTelefone.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbTelefone.setText("TELEFONE:");
        getContentPane().add(jlbTelefone);
        jlbTelefone.setBounds(20, 120, 100, 30);

        jlbCpf.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbCpf.setText("CPF:");
        getContentPane().add(jlbCpf);
        jlbCpf.setBounds(20, 80, 60, 30);

        jlbAdmissao.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbAdmissao.setText("ADMISSÃO:");
        getContentPane().add(jlbAdmissao);
        jlbAdmissao.setBounds(20, 200, 80, 30);

        jlbUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbUsuario.setText("USUARIO:");
        getContentPane().add(jlbUsuario);
        jlbUsuario.setBounds(20, 250, 70, 30);

        jlbSenha.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbSenha.setText("SENHA:");
        getContentPane().add(jlbSenha);
        jlbSenha.setBounds(20, 290, 80, 30);

        jtfNome.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        getContentPane().add(jtfNome);
        jtfNome.setBounds(70, 40, 250, 30);
        getContentPane().add(jtfTelefone);
        jtfTelefone.setBounds(90, 120, 160, 30);
        getContentPane().add(jtfCpf);
        jtfCpf.setBounds(70, 80, 140, 30);
        getContentPane().add(jtfAdmissao);
        jtfAdmissao.setBounds(90, 200, 170, 30);

        jbCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbCadastro.setText("CADASTRAR");
        jbCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(jbCadastro);
        jbCadastro.setBounds(10, 340, 130, 30);

        jbtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbtAlterar.setText("ALTERAR");
        jbtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtAlterar);
        jbtAlterar.setBounds(400, 340, 117, 30);

        jtbMostrarTodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "COD.", "NOME", "SETOR", "TELEFONE", "ADMISSÃO", "DEMISSÃO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbMostrarTodos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(400, 40, 710, 280);

        jlbTitulo1.setFont(new java.awt.Font("Miriam", 1, 14)); // NOI18N
        jlbTitulo1.setText("CADASTRAR  NOVO FUNCIONARIO:");
        getContentPane().add(jlbTitulo1);
        jlbTitulo1.setBounds(20, 10, 280, 15);

        jlbTitulo2.setFont(new java.awt.Font("Miriam", 1, 14)); // NOI18N
        jlbTitulo2.setText("TODOS OS FUNCIONARIOS CADASTRADOS: ");
        getContentPane().add(jlbTitulo2);
        jlbTitulo2.setBounds(400, 10, 350, 20);

        jcbSetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adiministrador", "Cozinheiro", "Caixa", "Garçom" }));
        jcbSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSetorActionPerformed(evt);
            }
        });
        getContentPane().add(jcbSetor);
        jcbSetor.setBounds(80, 160, 170, 30);

        jpfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jpfSenha);
        jpfSenha.setBounds(80, 290, 200, 30);

        jlbSetor1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbSetor1.setText("SETOR:");
        getContentPane().add(jlbSetor1);
        jlbSetor1.setBounds(20, 160, 80, 30);
        getContentPane().add(jtfUsuario1);
        jtfUsuario1.setBounds(80, 250, 200, 30);

        setBounds(115, 130, 1142, 416);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroActionPerformed
    
       
    }//GEN-LAST:event_jbCadastroActionPerformed

    private void jcbSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSetorActionPerformed

    private void jpfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfSenhaActionPerformed

    private void jbtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarActionPerformed
         AterarFuncionario At = new AterarFuncionario();  
         Principal.jdpPrincipal.add(At);
         At.setVisible(true);
         dispose();
         
         
    }//GEN-LAST:event_jbtAlterarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCadastro;
    private javax.swing.JButton jbtAlterar;
    private javax.swing.JComboBox jcbSetor;
    private javax.swing.JLabel jlbAdmissao;
    private javax.swing.JLabel jlbCpf;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbSenha;
    private javax.swing.JLabel jlbSetor1;
    private javax.swing.JLabel jlbTelefone;
    private javax.swing.JLabel jlbTitulo1;
    private javax.swing.JLabel jlbTitulo2;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTable jtbMostrarTodos;
    private javax.swing.JTextField jtfAdmissao;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfTelefone;
    private javax.swing.JTextField jtfUsuario1;
    // End of variables declaration//GEN-END:variables
}
