/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.main;

/**
 *
 * @author Philco
 */
public class CadastarBebida extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastarBebida
     */
    public CadastarBebida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbItens = new javax.swing.JLabel();
        jlbValor = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfNome1 = new javax.swing.JTextField();
        jtfCodigo1 = new javax.swing.JTextField();
        jbtCancelar = new javax.swing.JButton();
        jbtCadastrar = new javax.swing.JButton();
        jlbNome1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCadastrarBebida = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastrar Bebidas");
        getContentPane().setLayout(null);

        jlbItens.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbItens.setText("ITENS ADICIONADOS AO CARDAPIO:");
        getContentPane().add(jlbItens);
        jlbItens.setBounds(10, 150, 210, 30);

        jlbValor.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbValor.setText("VALOR UNITÃ�RIO:");
        getContentPane().add(jlbValor);
        jlbValor.setBounds(320, 20, 110, 30);
        getContentPane().add(jtfNome);
        jtfNome.setBounds(100, 20, 190, 30);
        getContentPane().add(jtfNome1);
        jtfNome1.setBounds(100, 20, 190, 30);
        getContentPane().add(jtfCodigo1);
        jtfCodigo1.setBounds(430, 20, 100, 30);

        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N
        jbtCancelar.setText("CANCELAR");
        getContentPane().add(jbtCancelar);
        jbtCancelar.setBounds(190, 80, 130, 30);

        jbtCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbtCadastrar.setText("CADASTRAR");
        jbtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtCadastrar);
        jbtCadastrar.setBounds(30, 80, 130, 30);

        jlbNome1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome1.setText("DESCRIÃ‡ÃƒO:");
        getContentPane().add(jlbNome1);
        jlbNome1.setBounds(30, 20, 80, 30);

        jtbCadastrarBebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "COD.", "DESCRIÃ‡ÃƒO", "VALOR"
            }
        ));
        jScrollPane1.setViewportView(jtbCadastrarBebida);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 740, 270);

        setBounds(310, 70, 777, 498);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtCadastrar;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JLabel jlbItens;
    private javax.swing.JLabel jlbNome1;
    private javax.swing.JLabel jlbValor;
    private javax.swing.JTable jtbCadastrarBebida;
    private javax.swing.JTextField jtfCodigo1;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNome1;
    // End of variables declaration//GEN-END:variables
}
