/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.main;

import static br.com.main.Principal.jdpPrincipal;

/**
 *
 * @author Philco
 */
public class Cardapio extends javax.swing.JInternalFrame {

    /**
     * Creates new form PedidoCliente
     */
    public Cardapio() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        popupMenu1 = new java.awt.PopupMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jScrollPane4 = new javax.swing.JScrollPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jtpTabs = new javax.swing.JTabbedPane();
        jPBebida = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtpPorcao = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtpSobremesa = new javax.swing.JTable();
        jpPorcao = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jtpSorvete = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        jtpLanche = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        jtpAlmoco = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jtpRodizio = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        jtpBife = new javax.swing.JTable();
        jPPrato = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtpBebida = new javax.swing.JTable();
        jbtAdicionarPedido = new javax.swing.JButton();
        jbtFinalizarPedido = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("CARDAPIO");
        getContentPane().setLayout(null);
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(100, -50, 5, 5);
        getContentPane().add(jTabbedPane4);
        jTabbedPane4.setBounds(200, -50, 5, 5);

        jPBebida.setLayout(null);

        jtpPorcao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "COD.", "NOME", "VALOR", "SELECIONE"
            }
        ));
        jScrollPane7.setViewportView(jtpPorcao);

        jPBebida.add(jScrollPane7);
        jScrollPane7.setBounds(10, 10, 750, 350);

        jtpTabs.addTab("PORÇOES", jPBebida);

        jPanel1.setLayout(null);

        jtpSobremesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "COD.", "NOME", "VALOR", "SELECIONE"
            }
        ));
        jScrollPane8.setViewportView(jtpSobremesa);

        jPanel1.add(jScrollPane8);
        jScrollPane8.setBounds(10, 10, 750, 350);

        jtpTabs.addTab("SOBREMESA", jPanel1);

        jpPorcao.setLayout(null);

        jtpSorvete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "COD.", "NOME", "VALOR", "SELECIONE"
            }
        ));
        jScrollPane16.setViewportView(jtpSorvete);

        jpPorcao.add(jScrollPane16);
        jScrollPane16.setBounds(10, 10, 750, 350);

        jtpTabs.addTab("SORVETE", jpPorcao);

        jPanel2.setLayout(null);

        jtpLanche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "COD.", "NOME", "VALOR", "SELECIONE"
            }
        ));
        jScrollPane17.setViewportView(jtpLanche);

        jPanel2.add(jScrollPane17);
        jScrollPane17.setBounds(10, 10, 750, 350);

        jtpTabs.addTab("LANCHES", jPanel2);

        jPanel4.setLayout(null);

        jtpAlmoco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "COD.", "NOME", "VALOR", "SELECIONE"
            }
        ));
        jScrollPane18.setViewportView(jtpAlmoco);

        jPanel4.add(jScrollPane18);
        jScrollPane18.setBounds(10, 10, 750, 350);

        jtpTabs.addTab("ALMOÇO BIFE LIVRE", jPanel4);

        jPanel5.setLayout(null);

        jtpRodizio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "COD.", "NOME", "VALOR", "SELECIONE"
            }
        ));
        jScrollPane19.setViewportView(jtpRodizio);

        jPanel5.add(jScrollPane19);
        jScrollPane19.setBounds(10, 10, 750, 350);

        jtpTabs.addTab("RODIZIO DE PIZZA", jPanel5);

        jPanel6.setLayout(null);

        jtpBife.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "COD.", "NOME", "VALOR", "SELECIONE"
            }
        ));
        jScrollPane20.setViewportView(jtpBife);

        jPanel6.add(jScrollPane20);
        jScrollPane20.setBounds(10, 10, 750, 350);

        jtpTabs.addTab("BIFE DE SOPAS", jPanel6);

        jPPrato.setLayout(null);

        jtpBebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "COD.", "NOME", "VALOR", "SELECIONE"
            }
        ));
        jScrollPane6.setViewportView(jtpBebida);

        jPPrato.add(jScrollPane6);
        jScrollPane6.setBounds(10, 10, 750, 350);

        jtpTabs.addTab("BEBIDAS", jPPrato);

        getContentPane().add(jtpTabs);
        jtpTabs.setBounds(10, 10, 780, 410);

        jbtAdicionarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbtAdicionarPedido.setText("ADICIONAR AO MEU PEDIDO");
        getContentPane().add(jbtAdicionarPedido);
        jbtAdicionarPedido.setBounds(350, 430, 220, 30);

        jbtFinalizarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbtFinalizarPedido.setText("FINALIZAR PEDIDO");
        jbtFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFinalizarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtFinalizarPedido);
        jbtFinalizarPedido.setBounds(610, 430, 160, 30);

        setBounds(310, 70, 802, 513);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFinalizarPedidoActionPerformed
       PedidoCliente obj=new PedidoCliente();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtFinalizarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JPanel jPBebida;
    private javax.swing.JPanel jPPrato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JButton jbtAdicionarPedido;
    private javax.swing.JButton jbtFinalizarPedido;
    private javax.swing.JPanel jpPorcao;
    private javax.swing.JTable jtpAlmoco;
    private javax.swing.JTable jtpBebida;
    private javax.swing.JTable jtpBife;
    private javax.swing.JTable jtpLanche;
    private javax.swing.JTable jtpPorcao;
    private javax.swing.JTable jtpRodizio;
    private javax.swing.JTable jtpSobremesa;
    private javax.swing.JTable jtpSorvete;
    private javax.swing.JTabbedPane jtpTabs;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
