/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.main;

/**
 *
 * @author Philco
 */
public class CardapioRefeicoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form CardapioRefeicoes
     */
    public CardapioRefeicoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbItens = new javax.swing.JLabel();
        jlbValor = new javax.swing.JLabel();
        jlbCodigo = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfCodigo1 = new javax.swing.JTextField();
        jbtCancelar = new javax.swing.JButton();
        jbtCadastrar = new javax.swing.JButton();
        jlbNome1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbRefeicao = new javax.swing.JTable();
        jcbTipoRefeicao = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastrar Refeições");
        getContentPane().setLayout(null);

        jlbItens.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbItens.setText("ITENS ADICIONADOS AO CARDAPIO:");
        getContentPane().add(jlbItens);
        jlbItens.setBounds(10, 180, 210, 30);

        jlbValor.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbValor.setText("VALOR DA REFEIÇÃO:");
        getContentPane().add(jlbValor);
        jlbValor.setBounds(380, 10, 130, 30);

        jlbCodigo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbCodigo.setText("TIPOS DE REFEIÇÃO:");
        getContentPane().add(jlbCodigo);
        jlbCodigo.setBounds(20, 10, 130, 30);
        getContentPane().add(jtfNome);
        jtfNome.setBounds(140, 70, 190, 30);
        getContentPane().add(jtfCodigo1);
        jtfCodigo1.setBounds(510, 10, 100, 30);

        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N
        jbtCancelar.setText("CANCELAR");
        getContentPane().add(jbtCancelar);
        jbtCancelar.setBounds(180, 130, 130, 30);

        jbtCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbtCadastrar.setText("CADASTRAR");
        jbtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtCadastrar);
        jbtCadastrar.setBounds(20, 130, 130, 30);

        jlbNome1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome1.setText("SABORES / TIPOS:");
        getContentPane().add(jlbNome1);
        jlbNome1.setBounds(20, 70, 110, 30);

        jtbRefeicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "SABORES", "TIPO DE REFEIÇÃO", "VALOR DA REFEIÇÃO"
            }
        ));
        jScrollPane1.setViewportView(jtbRefeicao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 740, 270);

        jcbTipoRefeicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALMOÇO BIFE LIVRE", "RODIZIO DE PIZZA", "BIFE DE SOPAS" }));
        getContentPane().add(jcbTipoRefeicao);
        jcbTipoRefeicao.setBounds(150, 10, 200, 30);

        setBounds(310, 70, 775, 521);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtCadastrar;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JComboBox jcbTipoRefeicao;
    private javax.swing.JLabel jlbCodigo;
    private javax.swing.JLabel jlbItens;
    private javax.swing.JLabel jlbNome1;
    private javax.swing.JLabel jlbValor;
    private javax.swing.JTable jtbRefeicao;
    private javax.swing.JTextField jtfCodigo1;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
