/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.main;

/**
 *
 * @author Philco
 */
public class Login extends javax.swing.JInternalFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpfSenha = new javax.swing.JPasswordField();
        jtfUsuario = new javax.swing.JTextField();
        jlbUsuario = new javax.swing.JLabel();
        jlbSenha = new javax.swing.JLabel();
        jbtAcessar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("LOGIN");
        getContentPane().setLayout(null);

        jpfSenha.setAutoscrolls(false);
        getContentPane().add(jpfSenha);
        jpfSenha.setBounds(180, 70, 180, 23);

        jtfUsuario.setFont(new java.awt.Font("Miriam", 0, 11)); // NOI18N
        jtfUsuario.setAutoscrolls(false);
        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jtfUsuario);
        jtfUsuario.setBounds(180, 30, 180, 23);

        jlbUsuario.setFont(new java.awt.Font("Miriam", 1, 12)); // NOI18N
        jlbUsuario.setText("Usuario:");
        getContentPane().add(jlbUsuario);
        jlbUsuario.setBounds(120, 30, 90, 20);

        jlbSenha.setFont(new java.awt.Font("Miriam", 1, 12)); // NOI18N
        jlbSenha.setText("Senha:");
        getContentPane().add(jlbSenha);
        jlbSenha.setBounds(120, 70, 70, 20);

        jbtAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbtAcessar.setText("ACESSAR");
        jbtAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtAcessar);
        jbtAcessar.setBounds(240, 110, 110, 30);

        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N
        jbtCancelar.setText("CANCELAR");
        getContentPane().add(jbtCancelar);
        jbtCancelar.setBounds(70, 110, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 19, 80, 74);

        setBounds(470, 200, 394, 180);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void jbtAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAcessarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAcessarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtAcessar;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JLabel jlbSenha;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
