/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.main;

/**
 *
 * @author Philco
 */
public class PedidoCozinha extends javax.swing.JInternalFrame {

    /**
     * Creates new form PedidoCozinha
     */
    public PedidoCozinha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPedidoCozinha = new javax.swing.JTable();
        jbtMandarPedido = new javax.swing.JButton();
        jcbPedidoCozinha = new javax.swing.JComboBox();
        jlbNome = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setClosable(true);
        setIconifiable(true);
        setTitle("PEDIDO PARA O COZINHEIRO");
        getContentPane().setLayout(null);

        jtbPedidoCozinha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Descrição", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jtbPedidoCozinha);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 490, 240);

        jbtMandarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbtMandarPedido.setText("MANDAR PEDIDO");
        jbtMandarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMandarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtMandarPedido);
        jbtMandarPedido.setBounds(350, 350, 160, 29);

        jcbPedidoCozinha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbPedidoCozinha);
        jcbPedidoCozinha.setBounds(20, 50, 220, 30);

        jlbNome.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome.setText("MESA QUE CONTEM PEDIDOS");
        getContentPane().add(jlbNome);
        jlbNome.setBounds(20, 10, 190, 30);

        setBounds(430, 150, 539, 422);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtMandarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMandarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtMandarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtMandarPedido;
    private javax.swing.JComboBox jcbPedidoCozinha;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JTable jtbPedidoCozinha;
    // End of variables declaration//GEN-END:variables
}
