/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.main;

import static br.com.main.Principal.jdpPrincipal;

/**
 *
 * @author Philco
 */
public class PedidoCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form PedidoCliente
     */
    public PedidoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPedido = new javax.swing.JTable();
        jlbNome = new javax.swing.JLabel();
        jlbNome1 = new javax.swing.JLabel();
        jlbNome2 = new javax.swing.JLabel();
        jtfTotal = new javax.swing.JTextField();
        jtfMesa = new javax.swing.JTextField();
        jbtVisualizarCardapio = new javax.swing.JButton();
        jbtGerarPedido = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Pedido Cliente");
        getContentPane().setLayout(null);

        jtPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "COD.", "PRODUTO", "VALOR", "QUANTIDADE"
            }
        ));
        jScrollPane1.setViewportView(jtPedido);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 737, 260);

        jlbNome.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome.setText("MEU PEDIDO");
        getContentPane().add(jlbNome);
        jlbNome.setBounds(20, 10, 70, 30);

        jlbNome1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome1.setText("NUMERO DA MESA:");
        getContentPane().add(jlbNome1);
        jlbNome1.setBounds(10, 320, 120, 30);

        jlbNome2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome2.setText("TOTAL DO PEDIDO:");
        getContentPane().add(jlbNome2);
        jlbNome2.setBounds(230, 320, 120, 30);
        getContentPane().add(jtfTotal);
        jtfTotal.setBounds(350, 320, 100, 30);
        getContentPane().add(jtfMesa);
        jtfMesa.setBounds(130, 320, 50, 30);

        jbtVisualizarCardapio.setText("VISUALIZAR CARDAPIO");
        jbtVisualizarCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVisualizarCardapioActionPerformed(evt);
            }
        });
        getContentPane().add(jbtVisualizarCardapio);
        jbtVisualizarCardapio.setBounds(590, 20, 160, 20);

        jbtGerarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbtGerarPedido.setText("GERAR PEDIDO");
        jbtGerarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGerarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtGerarPedido);
        jbtGerarPedido.setBounds(590, 320, 160, 30);

        setBounds(310, 70, 773, 399);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtVisualizarCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVisualizarCardapioActionPerformed
        Cardapio obj=new Cardapio();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtVisualizarCardapioActionPerformed

    private void jbtGerarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGerarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtGerarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtGerarPedido;
    private javax.swing.JButton jbtVisualizarCardapio;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbNome1;
    private javax.swing.JLabel jlbNome2;
    private javax.swing.JTable jtPedido;
    private javax.swing.JTextField jtfMesa;
    private javax.swing.JTextField jtfTotal;
    // End of variables declaration//GEN-END:variables
}
