/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.main;

/**
 *
 * @author Philco
 */
public class PedidoGarcom extends javax.swing.JInternalFrame {

    /**
     * Creates new form PedidoGarcom
     */
    public PedidoGarcom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtFinalizarEntrega = new javax.swing.JButton();
        jcbMesa = new javax.swing.JComboBox();
        jlbNome = new javax.swing.JLabel();
        jlbNome1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlPedidoGarcom = new javax.swing.JList();

        setClosable(true);
        setIconifiable(true);
        setTitle("PEDIDO PARA GARÇOM");
        getContentPane().setLayout(null);

        jbtFinalizarEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbtFinalizarEntrega.setText("FINALIZAR ENTREGA");
        jbtFinalizarEntrega.setPreferredSize(new java.awt.Dimension(129, 29));
        getContentPane().add(jbtFinalizarEntrega);
        jbtFinalizarEntrega.setBounds(178, 370, 180, 30);

        jcbMesa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbMesa);
        jcbMesa.setBounds(20, 50, 220, 30);

        jlbNome.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome.setText("MESA QUE CONTEM PEDIDOS");
        getContentPane().add(jlbNome);
        jlbNome.setBounds(20, 10, 190, 30);

        jlbNome1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbNome1.setText("RELAÇÃO DO PEDIDO REFERENTE A MESA");
        getContentPane().add(jlbNome1);
        jlbNome1.setBounds(20, 100, 250, 30);

        jlPedidoGarcom.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlPedidoGarcom);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 150, 340, 170);

        setBounds(480, 150, 397, 453);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtFinalizarEntrega;
    private javax.swing.JComboBox jcbMesa;
    private javax.swing.JList jlPedidoGarcom;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbNome1;
    // End of variables declaration//GEN-END:variables
}
