/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.main;

/**
 *
 * @author Philco
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmGerenciarSistema = new javax.swing.JMenu();
        jmiLogin = new javax.swing.JMenuItem();
        jmiLongout = new javax.swing.JMenuItem();
        jMenuCadastroFuncionario = new javax.swing.JMenu();
        jmiCadastarFuncionario = new javax.swing.JMenuItem();
        jmCardapio = new javax.swing.JMenu();
        jmiCadastarBebida = new javax.swing.JMenuItem();
        jmiCadastarprato = new javax.swing.JMenuItem();
        jmiCadastrarRefeicao = new javax.swing.JMenuItem();
        jmPedidoCliente = new javax.swing.JMenu();
        jmiCardapio = new javax.swing.JMenuItem();
        jmPedidoInterno = new javax.swing.JMenu();
        jmiPedidoCozinha = new javax.swing.JMenuItem();
        jmiPedidoGarcon = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiGerenciamentoCaixa = new javax.swing.JMenuItem();
        jmiRelatorioCaixa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROLE INTERNO RESTAURANTE");

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 973, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        jmGerenciarSistema.setText("GERENCIAR SISTEMA ");

        jmiLogin.setText("Entrar");
        jmiLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLoginActionPerformed(evt);
            }
        });
        jmGerenciarSistema.add(jmiLogin);

        jmiLongout.setText("Sair");
        jmiLongout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLongoutActionPerformed(evt);
            }
        });
        jmGerenciarSistema.add(jmiLongout);

        jMenuBar1.add(jmGerenciarSistema);

        jMenuCadastroFuncionario.setText("GERENCIADOR DE COLABORADORES");
        jMenuCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroFuncionarioActionPerformed(evt);
            }
        });

        jmiCadastarFuncionario.setText("Cadastrar Funcionario");
        jmiCadastarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastarFuncionarioActionPerformed(evt);
            }
        });
        jMenuCadastroFuncionario.add(jmiCadastarFuncionario);

        jMenuBar1.add(jMenuCadastroFuncionario);

        jmCardapio.setText("   GERENCIADOR DE CARDAPIOS   ");

        jmiCadastarBebida.setText("Cadastrar cardapio de bebidas");
        jmiCadastarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastarBebidaActionPerformed(evt);
            }
        });
        jmCardapio.add(jmiCadastarBebida);

        jmiCadastarprato.setText("Cadastrar cardapio rapido");
        jmiCadastarprato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastarpratoActionPerformed(evt);
            }
        });
        jmCardapio.add(jmiCadastarprato);

        jmiCadastrarRefeicao.setText("Cadastrar cardapio de refeições");
        jmiCadastrarRefeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarRefeicaoActionPerformed(evt);
            }
        });
        jmCardapio.add(jmiCadastrarRefeicao);

        jMenuBar1.add(jmCardapio);

        jmPedidoCliente.setText("PEDIDO CLIENTE");

        jmiCardapio.setText("Visualizar Cardapio");
        jmiCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCardapioActionPerformed(evt);
            }
        });
        jmPedidoCliente.add(jmiCardapio);

        jMenuBar1.add(jmPedidoCliente);

        jmPedidoInterno.setText("  GERENCIADOR DE PEDIDOS INTERNOS   ");

        jmiPedidoCozinha.setText("Pedido Cozinha");
        jmiPedidoCozinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPedidoCozinhaActionPerformed(evt);
            }
        });
        jmPedidoInterno.add(jmiPedidoCozinha);

        jmiPedidoGarcon.setText("Pedido Garçom");
        jmiPedidoGarcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPedidoGarconActionPerformed(evt);
            }
        });
        jmPedidoInterno.add(jmiPedidoGarcon);

        jMenuBar1.add(jmPedidoInterno);

        jMenu1.setText("GERENCIADOR CAIXA   ");

        jmiGerenciamentoCaixa.setText("Abrir caixa");
        jmiGerenciamentoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGerenciamentoCaixaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiGerenciamentoCaixa);

        jmiRelatorioCaixa.setText("Relatório caixa");
        jmiRelatorioCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioCaixaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelatorioCaixa);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setBounds(0, 0, 1009, 555);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCadastarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastarFuncionarioActionPerformed
        CadastroFuncionario obj=new CadastroFuncionario();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiCadastarFuncionarioActionPerformed

    private void jMenuCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCadastroFuncionarioActionPerformed

    private void jmiGerenciamentoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGerenciamentoCaixaActionPerformed
       AberturaCaixa obj=new AberturaCaixa();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiGerenciamentoCaixaActionPerformed

    private void jmiPedidoGarconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPedidoGarconActionPerformed
      PedidoGarcom obj=new PedidoGarcom();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiPedidoGarconActionPerformed

    private void jmiPedidoCozinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPedidoCozinhaActionPerformed
      PedidoCozinha obj=new PedidoCozinha();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiPedidoCozinhaActionPerformed

    private void jmiCadastarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastarBebidaActionPerformed
        CadastarBebida obj=new CadastarBebida();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiCadastarBebidaActionPerformed

    private void jmiCadastarpratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastarpratoActionPerformed
       CadastarCardapio obj=new CadastarCardapio();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiCadastarpratoActionPerformed

    private void jmiRelatorioCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioCaixaActionPerformed
       RelatorioCaixa obj=new RelatorioCaixa();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiRelatorioCaixaActionPerformed

    private void jmiLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLoginActionPerformed
       Login obj=new Login();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiLoginActionPerformed

    private void jmiLongoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLongoutActionPerformed
        dispose();
    }//GEN-LAST:event_jmiLongoutActionPerformed

    private void jmiCadastrarRefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarRefeicaoActionPerformed
       CardapioRefeicoes obj=new CardapioRefeicoes();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiCadastrarRefeicaoActionPerformed

    private void jmiCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCardapioActionPerformed
        Cardapio obj=new Cardapio();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiCardapioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastroFuncionario;
    public static javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu jmCardapio;
    private javax.swing.JMenu jmGerenciarSistema;
    private javax.swing.JMenu jmPedidoCliente;
    private javax.swing.JMenu jmPedidoInterno;
    private javax.swing.JMenuItem jmiCadastarBebida;
    private javax.swing.JMenuItem jmiCadastarFuncionario;
    private javax.swing.JMenuItem jmiCadastarprato;
    private javax.swing.JMenuItem jmiCadastrarRefeicao;
    private javax.swing.JMenuItem jmiCardapio;
    private javax.swing.JMenuItem jmiGerenciamentoCaixa;
    private javax.swing.JMenuItem jmiLogin;
    private javax.swing.JMenuItem jmiLongout;
    private javax.swing.JMenuItem jmiPedidoCozinha;
    private javax.swing.JMenuItem jmiPedidoGarcon;
    private javax.swing.JMenuItem jmiRelatorioCaixa;
    // End of variables declaration//GEN-END:variables
}
