/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.main;

/**
 *
 * @author Philco
 */
public class RelatorioCaixa extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerenciamentoCaixa
     */
    public RelatorioCaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCaixa = new javax.swing.JTable();
        jlbValorTotal = new javax.swing.JLabel();
        jtfValorTotal = new javax.swing.JTextField();
        jbtFinalizar = new javax.swing.JButton();
        jbtImpimir = new javax.swing.JButton();

        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setTitle("Gernciamento de Caixa");
        getContentPane().setLayout(null);

        jtbCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo do Pedido", "Numero da mesa", "Nome dos Pratos", "Quantidade", "Valor Unitario"
            }
        ));
        jtbCaixa.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jtbCaixa);
        jtbCaixa.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 10, 720, 430);

        jlbValorTotal.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbValorTotal.setText("MOVIMENTO DO DIA: ");
        getContentPane().add(jlbValorTotal);
        jlbValorTotal.setBounds(420, 460, 120, 30);
        getContentPane().add(jtfValorTotal);
        jtfValorTotal.setBounds(560, 460, 150, 30);

        jbtFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jbtFinalizar.setText("ENCERRAR CAIXA");
        getContentPane().add(jbtFinalizar);
        jbtFinalizar.setBounds(550, 510, 160, 30);

        jbtImpimir.setText("IMPRIMIR RELATORIO");
        getContentPane().add(jbtImpimir);
        jbtImpimir.setBounds(10, 520, 170, 23);

        setBounds(310, 40, 739, 582);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtFinalizar;
    private javax.swing.JButton jbtImpimir;
    private javax.swing.JLabel jlbValorTotal;
    private javax.swing.JTable jtbCaixa;
    private javax.swing.JTextField jtfValorTotal;
    // End of variables declaration//GEN-END:variables
}
